version: '3'

services:

  # nginx
  web: 
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./public:/var/www/html/public

  app:
    build: 
      dockerfile: ./php/Dockerfile
    volumes:
      - /var/www/html/vendor
      - .:/var/www/html


  database:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always



volumes:
  db-data: